import "./globals.css";
import { Oswald } from "next/font/google";
import NavBar from "./components/NavBar/NavBar";
import Footer from "./components/footer/footer";

const inter = Oswald({ subsets: ["latin"] });

export const metadata = {
  title: "Largo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} text-[#DFD3BB] bg-[#031723] w-screen overflow-x-hidden`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
