import './globals.css'
import { Oswald } from 'next/font/google'

const inter = Oswald({ subsets: ['latin'] })

export const metadata = {
  title: 'Largo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-[#DFD3BB] bg-[#031723]`}>{children}</body>
    </html>
  )
}
